// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLT66zLebqUA2rHClCHaMsM4sJ1S_MeRA',
    appId: '1:945077109618:web:9b2d82dc3de72efcb5d3eb',
    messagingSenderId: '945077109618',
    projectId: 'flutter-chat-app-743e0',
    authDomain: 'flutter-chat-app-743e0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-743e0.appspot.com',
    measurementId: 'G-8QK7KXXNCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1GTyTNimrGoVCFHWBvWWI_vZUuw0eQLY',
    appId: '1:945077109618:android:e7448dbe371def3cb5d3eb',
    messagingSenderId: '945077109618',
    projectId: 'flutter-chat-app-743e0',
    storageBucket: 'flutter-chat-app-743e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArxn_ISIvHXEpViv_pIr_WKowReUzaEik',
    appId: '1:945077109618:ios:08b5de630ce89e93b5d3eb',
    messagingSenderId: '945077109618',
    projectId: 'flutter-chat-app-743e0',
    storageBucket: 'flutter-chat-app-743e0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArxn_ISIvHXEpViv_pIr_WKowReUzaEik',
    appId: '1:945077109618:ios:08b5de630ce89e93b5d3eb',
    messagingSenderId: '945077109618',
    projectId: 'flutter-chat-app-743e0',
    storageBucket: 'flutter-chat-app-743e0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLT66zLebqUA2rHClCHaMsM4sJ1S_MeRA',
    appId: '1:945077109618:web:f3b8b8d4ac234c03b5d3eb',
    messagingSenderId: '945077109618',
    projectId: 'flutter-chat-app-743e0',
    authDomain: 'flutter-chat-app-743e0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-743e0.appspot.com',
    measurementId: 'G-G6FS1VZ8D2',
  );
}
